### ISSUE TITLE
Allow training Qwen Edit Plus without control images

### ISSUE THREAD

**Issue by MitPitt** [kohya-ss/musubi-tuner#682]
Qwen Edit 2509 can be used both as image-to-image, and text-to-image model. It doesn't need to have an input image.

I want to train a style lora that will work for both cases (I2I and T2I). So my datasets for this lora are split. Dataset A has images with captions. Dataset B has image pairs with edit instructions.

When I try to train with such a dataset (with `--edit_plus` flag), I get error: `AssertionError: Item must have control content for Qwen-Image-Edit` for images from dataset A.

I understand that text encoder works differently with control images present. It should look at context: if there's no control image specified, encode as in the non-edit_plus case. For UX sake, an extra flag can be provided in `dataset.toml`: `allow_no_control = true` so users can't accidentally mess up their datasets.

If there's a workaround right now, I would like to know about it

**Comment by kohya-ss** [comment]
I understand that you want to train using datasets which contains images with or without control images.

Unfortunately, this functionality is not currently available. I have implemented a trial version in the following branch, so could you please check that it works?

https://github.com/kohya-ss/musubi-tuner/tree/feat-qwen-image-edit-dataset-without-control-image

If there are no problems, I will merge it into main.

**Comment by FurkanGozukara** [comment]
> I understand that you want to train using datasets which contains images with or without control images.
> 
> Unfortunately, this functionality is not currently available. I have implemented a trial version in the following branch, so could you please check that it works?
> 
> https://github.com/kohya-ss/musubi-tuner/tree/feat-qwen-image-edit-dataset-without-control-image
> 
> If there are no problems, I will merge it into main.

I trained Qwen Image Edit Plus 2509 as a Qwen Image Base model without control images and results were horrible compared to just using black control images

Now I need to test your new branch :D

**Comment by FurkanGozukara** [comment]
i merged into main and gonna train now and compare 

i hope works as i expect https://github.com/FurkanGozukara/musubi-tuner

**Comment by MitPitt** [comment]
Branch does not work yet unfortunately. Excerpt from logs when trying to cache text encoder outputs:

```
INFO:__main__:Loading Qwen2.5-VL: F:\TRAINING\models\qwen_2.5_vl_7b.safetensors
INFO:musubi_tuner.qwen_image.qwen_image_utils:Loading state dict from F:\TRAINING\models\qwen_2.5_vl_7b.safetensors
INFO:musubi_tuner.qwen_image.qwen_image_utils:Loaded Qwen2.5-VL: <All keys matched successfully>
INFO:musubi_tuner.qwen_image.qwen_image_utils:Setting Qwen2.5-VL to dtype: torch.bfloat16
INFO:musubi_tuner.qwen_image.qwen_image_utils:Loading tokenizer from Qwen/Qwen-Image
INFO:__main__:Loading Qwen2.5-VL Processor for Edit
INFO:musubi_tuner.qwen_image.qwen_image_utils:Loading VL processor from Qwen/Qwen-Image-Edit
INFO:__main__:Encoding with Qwen2.5-VL
INFO:musubi_tuner.cache_text_encoder_outputs:Encoding dataset [0]
0it [00:00, ?it/s]WARNING:__main__:Item F:/TRAINING/dataset\49378646.jpg has no control content for Qwen-Image-Edit, saving without control images.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "F:\musubi-tuner\src\musubi_tuner\qwen_image_cache_text_encoder_outputs.py", line 179, in <module>
    main()
  File "F:\musubi-tuner\src\musubi_tuner\qwen_image_cache_text_encoder_outputs.py", line 151, in main
    cache_text_encoder_outputs.process_text_encoder_batches(
  File "F:\musubi-tuner\src\musubi_tuner\cache_text_encoder_outputs.py", line 116, in process_text_encoder_batches
    encode(batch[i : i + bs])
  File "F:\musubi-tuner\src\musubi_tuner\qwen_image_cache_text_encoder_outputs.py", line 149, in encode_for_text_encoder
    encode_and_save_batch(tokenizer, text_encoder, vl_processor, mode, batch, device, accelerator)
  File "F:\musubi-tuner\src\musubi_tuner\qwen_image_cache_text_encoder_outputs.py", line 51, in encode_and_save_batch
    for cc in item.control_content:
TypeError: 'NoneType' object is not iterable
```

For this dataset, I use .txt file captions

**Comment by FurkanGozukara** [comment]
@kohya-ss 

i got this error without control images

i made a fix : https://github.com/kohya-ss/musubi-tuner/pull/690

@MitPitt 

```
INFO:__main__:Loading Qwen2.5-VL: /workspace/Training_Models_Qwen/qwen_2.5_vl_7b_bf16.safetensors
INFO:musubi_tuner.qwen_image.qwen_image_utils:Loading state dict from /workspace/Training_Models_Qwen/qwen_2.5_vl_7b_bf16.safetensors
INFO:musubi_tuner.qwen_image.qwen_image_utils:Loaded Qwen2.5-VL: <All keys matched successfully>
INFO:musubi_tuner.qwen_image.qwen_image_utils:Setting Qwen2.5-VL to dtype: torch.bfloat16
INFO:musubi_tuner.qwen_image.qwen_image_utils:Loading tokenizer from Qwen/Qwen-Image
tokenizer_config.json: 4.69kB [00:00, 16.9MB/s]
vocab.json: 3.38MB [00:00, 68.8MB/s]
merges.txt: 1.67MB [00:00, 75.9MB/s]
added_tokens.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 605/605 [00:00<00:00, 3.55MB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 613/613 [00:00<00:00, 3.74MB/s]
chat_template.jinja: 2.43kB [00:00, 11.2MB/s]
INFO:__main__:Loading Qwen2.5-VL Processor for Edit
INFO:musubi_tuner.qwen_image.qwen_image_utils:Loading VL processor from Qwen/Qwen-Image-Edit
preprocessor_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 788/788 [00:00<00:00, 12.4MB/s]
tokenizer_config.json: 4.73kB [00:00, 15.2MB/s]
vocab.json: 2.78MB [00:00, 95.6MB/s]
merges.txt: 1.67MB [00:00, 89.5MB/s]
processor/tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11.4M/11.4M [00:00<00:00, 36.0MB/s]
added_tokens.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 605/605 [00:00<00:00, 4.06MB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 613/613 [00:00<00:00, 1.76MB/s]
chat_template.jinja: 1.02kB [00:00, 3.61MB/s]
video_preprocessor_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 904/904 [00:00<00:00, 14.4MB/s]
INFO:__main__:Encoding with Qwen2.5-VL
INFO:musubi_tuner.cache_text_encoder_outputs:Encoding dataset [0]
0it [00:00, ?it/s]WARNING:__main__:Item /workspace/28_imgs_1328_v3/1_ohwx/10.jpg has no control content for Qwen-Image-Edit, saving without control images.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/workspace/SECourses_Musubi_Trainer2/./musubi-tuner/src/musubi_tuner/qwen_image_cache_text_encoder_outputs.py", line 179, in <module>
    main()
  File "/workspace/SECourses_Musubi_Trainer2/./musubi-tuner/src/musubi_tuner/qwen_image_cache_text_encoder_outputs.py", line 151, in main
    cache_text_encoder_outputs.process_text_encoder_batches(
  File "/workspace/SECourses_Musubi_Trainer2/musubi-tuner/src/musubi_tuner/cache_text_encoder_outputs.py", line 116, in process_text_encoder_batches
    encode(batch[i : i + bs])
  File "/workspace/SECourses_Musubi_Trainer2/./musubi-tuner/src/musubi_tuner/qwen_image_cache_text_encoder_outputs.py", line 149, in encode_for_text_encoder
    encode_and_save_batch(tokenizer, text_encoder, vl_processor, mode, batch, device, accelerator)
  File "/workspace/SECourses_Musubi_Trainer2/./musubi-tuner/src/musubi_tuner/qwen_image_cache_text_encoder_outputs.py", line 51, in encode_and_save_batch
    for cc in item.control_content:
TypeError: 'NoneType' object is not iterable
Text encoder caching failed with error code 0
09:55:41-811992 INFO     Training completed successfully.      
```

**Comment by MitPitt** [comment]
> i made a fix : [#690](https://github.com/kohya-ss/musubi-tuner/pull/690)

@FurkanGozukara In your commit:
```
break # If any item lacks control content, process entire batch without control images
```

This is not robust, a single batch can have images with and without control.

**Comment by kohya-ss** [comment]
I've updated the branch. 

> This is not robust, a single batch can have images with and without control.

This is guaranteed by Aspect Ratio Bucketing with control images, if my implementation is correct :)

**Comment by MitPitt** [comment]
Caching worked fine now. Having a new problem with sampling (with `--sample_at_first`)

```AssertionError: control_image_path not found in sample prompt```

It dislikes the fact that some of my sample prompts in `prompts.txt` don't have `--ci` control images

**Comment by kohya-ss** [comment]
Hmm, that's definitely necessary. I updated the branch.

**Comment by MitPitt** [comment]
Latest update seems to be working when:
- all prompts have `--ci` 
- no prompts have `--ci`

But does not work when prompts.txt has different prompts with and without `--ci`. With error:

```
Traceback (most recent call last):
  File "F:\musubi-tuner\src\musubi_tuner\qwen_image_train_network.py", line 497, in <module>
    main()
  File "F:\musubi-tuner\src\musubi_tuner\qwen_image_train_network.py", line 493, in main
    trainer.train(args)
  File "F:\musubi-tuner\src\musubi_tuner\hv_train_network.py", line 1708, in train
    sample_parameters = self.process_sample_prompts(args, accelerator, args.sample_prompts)
  File "F:\musubi-tuner\src\musubi_tuner\qwen_image_train_network.py", line 107, in process_sample_prompts
    control_image_nps[control_image_path] = control_image_np
TypeError: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "C:\Users\Mit\AppData\Local\mise\installs\python\3.10.16\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Mit\AppData\Local\mise\installs\python\3.10.16\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\musubi-tuner\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\musubi-tuner\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 50, in main
    args.func(args)
  File "F:\musubi-tuner\venv\lib\site-packages\accelerate\commands\launch.py", line 1213, in launch_command
    simple_launcher(args)
  File "F:\musubi-tuner\venv\lib\site-packages\accelerate\commands\launch.py", line 795, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\musubi-tuner\\venv\\Scripts\\python.exe', 'src/musubi_tuner/qwen_image_train_network.py', '--config_file', 'F:\\TRAINING\\config.toml']' returned non-zero exit status 1.
```

**Comment by kohya-ss** [comment]
Sorry for taking up your time. I don't have time to prepare a dataset and test sample prompts.

I've updated it again, so hopefully it works now.

**Comment by MitPitt** [comment]
Sadly still not quite working. Now with error:

```
Traceback (most recent call last):
  File "F:\musubi-tuner\src\musubi_tuner\qwen_image_train_network.py", line 497, in <module>
    main()
  File "F:\musubi-tuner\src\musubi_tuner\qwen_image_train_network.py", line 493, in main
    trainer.train(args)
  File "F:\musubi-tuner\src\musubi_tuner\hv_train_network.py", line 1708, in train
    sample_parameters = self.process_sample_prompts(args, accelerator, args.sample_prompts)
  File "F:\musubi-tuner\src\musubi_tuner\qwen_image_train_network.py", line 141, in process_sample_prompts
    control_image_paths = None if not is_edit else prompt_dict_copy["control_image_path"]
KeyError: 'control_image_path'
Traceback (most recent call last):
  File "C:\Users\Mit\AppData\Local\mise\installs\python\3.10.16\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Mit\AppData\Local\mise\installs\python\3.10.16\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\musubi-tuner\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\musubi-tuner\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 50, in main
    args.func(args)
  File "F:\musubi-tuner\venv\lib\site-packages\accelerate\commands\launch.py", line 1213, in launch_command
    simple_launcher(args)
  File "F:\musubi-tuner\venv\lib\site-packages\accelerate\commands\launch.py", line 795, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\musubi-tuner\\venv\\Scripts\\python.exe', 'src/musubi_tuner/qwen_image_train_network.py', '--config_file', 'F:\\TRAINING\\config.toml']' returned non-zero exit status 1.
```

In case you want prompts for testing:

```
photo of a alice --w 1024 --h 1024 --s 20 --d 1
photo of a bob --w 1024 --h 1024 --s 20 --d 2
invert colors --w 1024 --h 1024 --s 20 --d 3 --ci \path\to\image\any_image_1.jpg
invert colors --w 1024 --h 1024 --s 20 --d 4 --ci \path\to\image\any_image_2.jpg
```

You can use any minimal dataset that you already have (with or without control), since that feature already seems to be working fine.

**Comment by FurkanGozukara** [comment]
i am training without samples it is working

i wonder the results though still in training

**Comment by kohya-ss** [comment]
I updated the branch. I tested it, so I think it works.

I don't think it will have much of an impact on the quality of the training results...

**Comment by FurkanGozukara** [comment]
> I updated the branch. I tested it, so I think it works.
> 
> I don't think it will have much of an impact on the quality of the training results...

yes i also trained nice results thanks a lot

our biggest issue is slowness on Windows :( 

with 15 block swapping, FP8 scaled and 1328 resolution my best speed is 6.5 second / it on Windows - RTX 5090

On same settings Linux it is  3.85 second / it - huge difference

we really need to solve this RAM - GPU thing - even if it uses more RAM, shared VRAM still ok for high RAM people, can be optional as you said

**Comment by MitPitt** [comment]
After testing, branch seems to be working as intended, I say merge.

**Comment by FurkanGozukara** [comment]
it is working amazing

<img width="731" height="944" alt="Image" src="https://github.com/user-attachments/assets/572cb07a-2470-4880-8702-040856358dfd" />

**Comment by zhangquanwei962** [comment]
> it is working amazing
> 
> <img alt="Image" width="731" height="944" src="https://private-user-images.githubusercontent.com/19240467/506819521-572cb07a-2470-4880-8702-040856358dfd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE3Mjg2OTYsIm5iZiI6MTc2MTcyODM5NiwicGF0aCI6Ii8xOTI0MDQ2Ny81MDY4MTk1MjEtNTcyY2IwN2EtMjQ3MC00ODgwLTg3MDItMDQwODU2MzU4ZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI5VDA4NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNDgwY2FmYmNiYWRhNjEyNWNhMjEzZDVhZDMyZmZlYzVmNmZlMjU4ZWVlMDE3MGM5NzA1NzE2YjZkNDIyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y-jX6Q6gCAdNI9_YbbRvUWUN70ArdnpunQmiKkU6TR0">

Hi, I'm wondering if qwen-image-edit-2509 was trained using a text-to-image (T2I) paradigm instead of an image-to-image (I2I) approach, and then you're applying the trained model to image editing tasks?

**Comment by FurkanGozukara** [comment]
> > it is working amazing
> > <img alt="Image" width="731" height="944" src="https://private-user-images.githubusercontent.com/19240467/506819521-572cb07a-2470-4880-8702-040856358dfd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE3Mjg2OTYsIm5iZiI6MTc2MTcyODM5NiwicGF0aCI6Ii8xOTI0MDQ2Ny81MDY4MTk1MjEtNTcyY2IwN2EtMjQ3MC00ODgwLTg3MDItMDQwODU2MzU4ZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI5VDA4NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNDgwY2FmYmNiYWRhNjEyNWNhMjEzZDVhZDMyZmZlYzVmNmZlMjU4ZWVlMDE3MGM5NzA1NzE2YjZkNDIyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y-jX6Q6gCAdNI9_YbbRvUWUN70ArdnpunQmiKkU6TR0">
> 
> Hi, I'm wondering if qwen-image-edit-2509 was trained using a text-to-image (T2I) paradigm instead of an image-to-image (I2I) approach, and then you're applying the trained model to image editing tasks?

I trained with just text to images and it still works with this prompt way - no control paired images used

**Comment by zhangquanwei962** [comment]
> I trained with just text to images and it still works with this prompt way - no control paired images used

Did you test the t2i mode? is it full finetune or lora? When you train the text to images, the edited result is almost consistent with the original qwen-image-edit-2509. And can you tell me what your proposal is to do text to images if only using in edit mode? Thank you

**Comment by FurkanGozukara** [comment]
@kohya-ss latest updates broken this feature again can you fix?


used dataset

```
[[datasets]]
image_directory = "C:/Users/Furkan/Pictures/28_imgs_1328/1_ohwx"
num_repeats = 1
cache_directory = "C:/Users/Furkan/Pictures/28_imgs_1328/1_ohwx/cache_dir"

[general]
resolution = [ 1328, 1328]
caption_extension = ".txt"
batch_size = 1
enable_bucket = false
bucket_no_upscale = false
```



```
INFO:musubi_tuner.qwen_image.qwen_image_utils:Loading VL processor from Qwen/Qwen-Image-Edit
INFO:__main__:Encoding with Qwen2.5-VL
INFO:musubi_tuner.cache_text_encoder_outputs:Encoding dataset [0]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "F:\SECourses_Musubi_Trainer_v16\SECourses_Musubi_Trainer\musubi-tuner\src\musubi_tuner\qwen_image_cache_text_encoder_outputs.py", line 176, in <module>
    main()
  File "F:\SECourses_Musubi_Trainer_v16\SECourses_Musubi_Trainer\musubi-tuner\src\musubi_tuner\qwen_image_cache_text_encoder_outputs.py", line 148, in main
    cache_text_encoder_outputs.process_text_encoder_batches(
  File "F:\SECourses_Musubi_Trainer_v16\SECourses_Musubi_Trainer\musubi-tuner\src\musubi_tuner\cache_text_encoder_outputs.py", line 116, in process_text_encoder_batches
    encode(batch[i : i + bs])
  File "F:\SECourses_Musubi_Trainer_v16\SECourses_Musubi_Trainer\musubi-tuner\src\musubi_tuner\qwen_image_cache_text_encoder_outputs.py", line 146, in encode_for_text_encoder
    encode_and_save_batch(tokenizer, text_encoder, vl_processor, mode, batch, device, accelerator)
  File "F:\SECourses_Musubi_Trainer_v16\SECourses_Musubi_Trainer\musubi-tuner\src\musubi_tuner\qwen_image_cache_text_encoder_outputs.py", line 46, in encode_and_save_batch
    assert item.control_content is not None and len(item.control_content) > 0, (
AssertionError: Item C:/Users/Furkan/Pictures/28_imgs_1328/1_ohwx\a.jpg must have control content for Qwen-Image-Edit
Text encoder caching failed with error code 1
02:11:52-927161 ERROR    Training failed with exit code: 1

```

**Comment by kohya-ss** [comment]
> [@kohya-ss](https://github.com/kohya-ss) latest updates broken this feature again can you fix?

#704 is merged :)

**Comment by FurkanGozukara** [comment]
> > [@kohya-ss](https://github.com/kohya-ss) latest updates broken this feature again can you fix?
> 
> [#704](https://github.com/kohya-ss/musubi-tuner/pull/704) is merged :)

thank you so much I had forgatten that i was using merged branch :D
